//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doc.insure.entities.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class docInsureEntities : DbContext
    {
        public docInsureEntities()
            : base("name=docInsureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentCategory> DocumentCategories { get; set; }
        public virtual DbSet<RelationShipType> RelationShipTypes { get; set; }
        public virtual DbSet<TrustedContact> TrustedContacts { get; set; }
        public virtual DbSet<TrustedContactStatu> TrustedContactStatus { get; set; }
        public virtual DbSet<DocumentView> DocumentViews { get; set; }
        public virtual DbSet<TrustedContactView> TrustedContactViews { get; set; }
    }
}
