//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doc.insure.entities.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustedContactStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrustedContactStatu()
        {
            this.TrustedContacts = new HashSet<TrustedContact>();
        }
    
        public int TrustedContactStatusId { get; set; }
        public string TrustedContactStatusDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrustedContact> TrustedContacts { get; set; }
    }
}
