//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doc.insure.entities.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustedContactView
    {
        public int TrustedContactId { get; set; }
        public int AppUserId { get; set; }
        public string AppUserFullName { get; set; }
        public int ContactAppUserId { get; set; }
        public string ContactAppUserFullName { get; set; }
        public System.DateTime TrustedContactCreated { get; set; }
        public string TrustedContactEmail { get; set; }
        public string TrustedContactFullName { get; set; }
        public int RelationShipTypeId { get; set; }
        public string RelationShipTypeDesc { get; set; }
        public System.Guid TrustedContactGuid { get; set; }
        public Nullable<int> TrustedContactStatusId { get; set; }
        public string TrustedContactStatusDesc { get; set; }
    }
}
